defaults:
  - isaaclab_pi05_pirl_realworld_tabero_tacimg_task6_step23000_fixed_gripper_shared_sim_smoke
  - _self_

runner:
  logger:
    experiment_name: ${oc.env:REALWORLD_TABERO_RANDOMIZATION_RUN_ID}
  max_epochs: 1
  max_steps: 1
  only_eval: false
  val_check_interval: -1
  save_interval: 1

env:
  train:
    rollout_epoch: 1
    total_num_envs: 1
    max_steps_per_rollout_epoch: 300
    max_episode_steps: 300
    video_cfg:
      save_video: true
      video_base_dir: ${runner.logger.log_path}/${runner.logger.experiment_name}/video/train
    init_params:
      max_episode_steps: ${..max_episode_steps}
      realworld_config_dir: /home_shared/rashare/qixuan/Tabero/RLinf/examples/embodiment/config/env/realworld_profiles/gentle_grasp_task6_uniform_randomization
      gripper_diagnostics_path: ${runner.logger.log_path}/${runner.logger.experiment_name}/gripper_diagnostics.jsonl
  eval:
    rollout_epoch: 1
    total_num_envs: 1
    max_steps_per_rollout_epoch: 300
    max_episode_steps: 300
    video_cfg:
      save_video: true
      video_base_dir: ${runner.logger.log_path}/${runner.logger.experiment_name}/video/eval
    init_params:
      max_episode_steps: ${..max_episode_steps}
      realworld_config_dir: /home_shared/rashare/qixuan/Tabero/RLinf/examples/embodiment/config/env/realworld_profiles/gentle_grasp_task6_uniform_randomization

actor:
  micro_batch_size: 1
  global_batch_size: 1
  fsdp_config:
    gradient_checkpointing: true
    gradient_checkpointing_use_reentrant: false
